- hosts: all
  become: true
  roles:
    - docker  # Calls the Docker role defined in ansible/roles/docker/tasks/main.yml

  tasks:
    - name: Log in to Azure Container Registry
      shell: echo "{{ lookup('env', 'ACR_ADMIN_PASSWORD') }}" | docker login "{{ lookup('env', 'ACR_LOGIN_SERVER') }}" -u "{{ lookup('env', 'ACR_ADMIN_USERNAME') }}" --password-stdin

    - name: Pull Docker image from ACR
      shell: docker pull {{ lookup('env', 'ACR_LOGIN_SERVER') }}/flask_app:{{ lookup('env', 'IMAGE_TAG') }}

    - name: Run Flask Docker container
      shell: |
        docker rm -f flask_app || true
        docker run -d --name flask_app -p 80:5000 {{ lookup('env', 'ACR_LOGIN_SERVER') }}/flask_app:{{ lookup('env', 'IMAGE_TAG') }}
