---
- hosts: all
  become: true
  tasks:
    - name: Update apt and install prerequisites
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create application directory
      file:
        path: /home/{{ ansible_user }}/app
        state: directory
        mode: '0755'

    - name: Copy application code to VM
      copy:
        src: ../app/  # Path to your local app directory
        dest: /home/{{ ansible_user }}/app
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Build Docker image on VM
      command: docker build -t flask_app:latest /home/{{ ansible_user }}/app
      args:
        chdir: /home/{{ ansible_user }}/app

    - name: Run Docker container
      command: docker run -d --name flask_app -p 80:5000 flask_app:latest
      ignore_errors: true  # Ignore if container is already running

    - name: Restart Docker container if already running
      command: docker restart flask_app
      when: result is failed