name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ADMIN_USERNAME: "azureuser"
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      RESOURCE_GROUP_NAME: "Network-RG"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Download Terraform state file
        uses: actions/download-artifact@v2
        with:
            name: terraform-state
            path: terraform  # Download into the 'terraform' directory
        continue-on-error: true
      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init
      - name: Check if Resource Group Exists in Azure
        id: rg_exists_check
        run: |
          if az group show --name $RESOURCE_GROUP_NAME --subscription $AZURE_SUBSCRIPTION_ID; then
            echo "exists_in_azure=true" >> $GITHUB_ENV
          else
            echo "exists_in_azure=false" >> $GITHUB_ENV
          fi
  
      - name: Check if Resource Group Exists in Terraform State
        id: rg_state_check
        run: |
            if terraform state show data.azurerm_resource_group.rg; then
              echo "exists_in_state=true" >> $GITHUB_ENV
            else
              echo "exists_in_state=false" >> $GITHUB_ENV
            fi    
      - name: Import Resource Group into Terraform State if Needed
        if: env.exists_in_azure == 'true' && env.exists_in_state == 'false'
        run: terraform import azurerm_resource_group.rg "/subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP_NAME }}"
    
      - working-directory: terraform
        run: terraform apply -auto-approve -var="admin_username=${{ env.ADMIN_USERNAME }}" -var="admin_password=${{ env.ADMIN_PASSWORD }}"
      - name: Save Terraform state file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform-state
          path: terraform/terraform.tfstate

      - name: Retrieve output variables from Terraform
        id: get_ip
        working-directory: terraform
        run: |
          # Check Terraform outputs and export them as environment variables
          echo "Retrieving Terraform outputs for debug..."
          terraform output
      
          # Set outputs if they exist; otherwise, exit with error for missing outputs
          if terraform output -raw public_ip &>/dev/null; then
            echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_ENV
          else
            echo "Error: public_ip output not found in Terraform state." >&2
            exit 1
          fi
      
          if terraform output -raw acr_login_server &>/dev/null; then
            echo "acr_login_server=$(terraform output -raw acr_login_server)" >> $GITHUB_ENV
          else
            echo "Error: acr_login_server output not found in Terraform state." >&2
            exit 1
          fi
      
          if terraform output -raw acr_admin_username &>/dev/null; then
            echo "acr_admin_username=$(terraform output -raw acr_admin_username)" >> $GITHUB_ENV
          else
            echo "Error: acr_admin_username output not found in Terraform state." >&2
            exit 1
          fi
      
          if terraform output -raw acr_admin_password &>/dev/null; then
            echo "acr_admin_password=$(terraform output -raw acr_admin_password)" >> $GITHUB_ENV
          else
            echo "Error: acr_admin_password output not found in Terraform state." >&2
            exit 1
          fi
      
      
      
      - name: Log in to Azure Container Registry
        run: |
          echo "${{ env.acr_admin_password }}" | docker login ${{ env.acr_login_server }} -u ${{ env.acr_admin_username }} --password-stdin
      
      - name: Build Docker image
        working-directory: app
        run: |
          docker build -t flask_app:${{ github.sha }} .
          docker tag flask_app:${{ github.sha }} ${{ env.acr_login_server }}/flask_app:${{ github.sha }}
      
      - name: Push Docker image to ACR
        working-directory: app
        run: |
          docker push ${{ env.acr_login_server }}/flask_app:${{ github.sha }}
      
      - name: Update Ansible inventory with VM IP
        run: |
          echo "[all]" > ansible/inventory.ini
          echo "${{ env.public_ip }} ansible_user=${{ env.ADMIN_USERNAME }} ansible_password=${{ env.ADMIN_PASSWORD }} ansible_connection=ssh ansible_port=22" >> ansible/inventory.ini
      
      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
      
      - name: Run Ansible Playbook to configure server and deploy Docker container
        env:
          ACR_LOGIN_SERVER: ${{ env.acr_login_server }}
          ACR_ADMIN_USERNAME: ${{ env.acr_admin_username }}
          ACR_ADMIN_PASSWORD: ${{ env.acr_admin_password }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
      